package me.ferrybig.javacoding.neuralnetwork.gui.training;

import javax.swing.border.TitledBorder;

/**
 *
 * @author Fernando
 */
public final class WorkerForm extends javax.swing.JComponent {

	private double initialError;
	private double initialErrorLog;
	private long maxIterations;
	private double targetError;
	private double targetErrorLog;
	private long iterations = -1;
	private double error;
	private String title = "";
	private final TitledBorder border = javax.swing.BorderFactory.createTitledBorder(" ");

	public WorkerForm() {
		this.initComponents();
		setMaxIterations(1);
		setTargetError(0);
		setInitialError(1);
		setIterations(0);
		setError(0.5);
		setTitle(" ");
	}

	public WorkerForm(double initialError, double targetError, long maxIterations) {
		this();
		setMaxIterations(maxIterations);
		setTargetError(targetError);
		setInitialError(initialError);
	}

	public double getInitialError() {
		return initialError;
	}

	/**
	 * @param initialError 
	 * @beaninfo
     *        bound: true
     *  description: Initial error, used in internal calculations
	 */
	public void setInitialError(double initialError) {
		this.firePropertyChange("initialError", this.maxIterations, maxIterations);
		this.initialError = initialError;
		this.initialErrorLog = Math.log(initialError);
	}

	public long getMaxIterations() {
		return maxIterations;
	}

	/**
	 * @param maxIterations 
	 * @beaninfo
     *        bound: true
     *  description: Maximum iterations, used in internal calculations
	 */
	public void setMaxIterations(long maxIterations) {
		this.firePropertyChange("maxIterations", this.maxIterations, maxIterations);
		this.maxIterations = maxIterations;
	}

	public double getTargetError() {
		return targetError;
	}

	/**
	 * @param targetError 
	 * @beaninfo
     *        bound: true
     *  description: Target error, used in internal calculations
	 */
	public void setTargetError(double targetError) {
		this.firePropertyChange("targetError", this.iterations, iterations);
		this.targetError = targetError;
		this.targetErrorLog = Math.log(targetError);
	}

	public long getIterations() {
		return iterations;
	}

	/**
	 * @param iterations 
	 * @beaninfo
     *        bound: true
     *  description: iterations, amount of iterations
	 */
	public void setIterations(long iterations) {
		this.firePropertyChange("iterations", this.iterations, iterations);
		this.iterations = iterations;
		this.iterationBar.setValue((int) (iterations * 100 / maxIterations));
	}

	public double getError() {
		return error;
	}

	/**
	 * @param error 
	 * @beaninfo
     *        bound: true
     *  description: error of the calculation
	 */
	public void setError(double error) {
		this.firePropertyChange("error", this.error, error);
		this.error = error;
		this.errorBar.setString("Error rate: " + error);
		double d = (Math.log(error) - initialErrorLog) / (targetErrorLog - initialErrorLog);
		d *= 100;
		d = 100 - d;
		this.errorBar.setValue((int) d);
	}

	public String getTitle() {
		return title;
	}

	/**
	 * @param title
	 * @beaninfo
     *        bound: true
     *  description: title of the form
	 */
	public void setTitle(String title) {
		this.firePropertyChange("title", this.title, title);
		border.setTitle(this.title = title);
		this.setBorder(border);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        errorBar = new javax.swing.JProgressBar();
        iterationBar = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridBagLayout());

        errorBar.setString(" ");
        errorBar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(errorBar, gridBagConstraints);

        iterationBar.setString(" ");
        iterationBar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(iterationBar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar errorBar;
    private javax.swing.JProgressBar iterationBar;
    // End of variables declaration//GEN-END:variables

}
