package me.ferrybig.javacoding.neuralnetwork.gui.network;

import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Fernando
 */
public class ResizeForm extends javax.swing.JPanel {

	private ResizeLayerForm[] layers = new ResizeLayerForm[] {
		new ResizeLayerForm(),
		new ResizeLayerForm(),
	};
	private JPanel panel;
	
	/**
	 * Creates new form ResizeForm
	 */
	public ResizeForm() {
		initComponents();
		initLayout();
	}
	
	public void setLayers(int[] layers) {
		if(layers.length < 2) {
			throw new IllegalArgumentException("Should have input and output layer");
		}
		this.layers = new ResizeLayerForm[layers.length];
		this.layers[0].setRemoveable(false);
		this.layers[layers.length - 1].setRemoveable(false);
		for(int i = 0; i < layers.length; i++) {
			if(layers[i] <= 0) {
				throw new IllegalArgumentException("Layers should be greater than 0");
			}
			this.layers[i].setValue(layers[i]);
			if(i == 0) {
				this.layers[i].setTitle("Input layer");
			} else if (i == layers.length - 1) {
				this.layers[i].setTitle("Output layer");
			} else {
				this.layers[i].setTitle("Layer " + i);
			}
		}
	}

	public int[] getLayers() {
		int[] newLayer = new int[layers.length];
		for(int i = 0; i < layers.length; i++) {
			newLayer[i] = layers[i].getValue();
		}
		return newLayer;
	}
	
	private void initLayout() {
		JPanel panel = new JPanel();
		panel.setLayout(new GridLayout(0, 1));
		for(int i = 0; i < layers.length; i++) {
			final int index = i;
			if(i != 0) {
				JButton button = new JButton();
				button.setText("Add layer");
				button.addActionListener(evt -> {
					insertLayer(index);
				});
				panel.add(button);
			}
			ResizeLayerForm form = layers[i];
			form.setRemoveAction(() -> removeLayer(index));
			panel.add(form);
		}
		if(this.panel != null)
			this.mainPanel.remove(this.panel);
		GridBagConstraints con = new GridBagConstraints();
		con.fill = GridBagConstraints.HORIZONTAL;
		con.weightx = 1;
		con.weighty = 1;
		this.mainPanel.add(panel, con);
		this.panel = panel;
	}
	
	public void insertLayer(int index) {
		int[] newLayer = new int[layers.length + 1];
		for(int i = 0; i < index; i++) {
			newLayer[i] = layers[i].getValue();
		}
		newLayer[index] = 1;
		for(int i = 0; i < (layers.length - index); i++) {
			newLayer[index + i + 1] = layers[index + i].getValue();
		}
		setLayers(newLayer);
		initLayout();
	}
	
	public void removeLayer(int index) {
		int[] newLayer = new int[layers.length - 1];
		for(int i = 0; i < index; i++) {
			newLayer[i] = layers[i].getValue();
		}
		for(int i = 1; i < (layers.length - index); i++) {
			newLayer[index + i - 1] = layers[index + i].getValue();
		}
		setLayers(newLayer);
		initLayout();
	}

	@Override
	public Dimension getPreferredSize() {
		if(this.isPreferredSizeSet())
			return super.getPreferredSize();
		else
			return new Dimension(100, 100);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scroll = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        mainPanel.setLayout(new java.awt.GridBagLayout());
        scroll.setViewportView(mainPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(scroll, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
